name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: leoncvlt/loconotion
          path: loconotion
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo
      - name: Download and install chromedriver
        run: sudo apt install chromium-chromedriver
      - name: Install Loconotion dependencies
        run: |
          # pip install -r loconotion/requirements.txt
          pip install --upgrade pip
          # 先安装基础依赖，忽略版本锁定
          pip install urllib3==1.26.18 requests==2.31.0 selenium==3.141.0
          pip install beautifulsoup4 lxml click python-dateutil pytz
          # 然后安装其他依赖但跳过已安装的包
          pip install -r loconotion/requirements.txt --force-reinstall --no-deps
          # 最后确保关键包是兼容版本
          pip install --upgrade urllib3==1.26.18
          
      - name: Run Loconotion
        run: |
          python3 loconotion/loconotion --chromedriver chromedriver "pages_repo/site.toml"
      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
